"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[┌─](bold fg:color_bg3)\
$directory\
$git_branch\
$git_status\
$fill\
$azure\
$terraform\
$docker_context\
$golang\
$nodejs\
$python\
$dotnet\
$line_break\
[└](bold fg:color_bg3)$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[directory]
style = "bold fg:color_purple"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
format = '[[$symbol$branch](bold fg:color_yellow)]($style) '

[git_status]
format = '([[$all_status$ahead_behind](fg:color_orange) ]($style))'
conflicted = "≠"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕"
untracked = "?"
stashed = "$"
modified = "~"
staged = "+"
renamed = "»"
deleted = "✘"

[azure]
symbol = "󰠅 "
style = "fg:color_blue"
format = "[$symbol$subscription]($style) "
disabled = false

[terraform]
symbol = "󱁢 "
format = '[$symbol$workspace]($style) '
style = "fg:color_purple"

[docker_context]
symbol = " "
format = '[$symbol$context]($style) '
style = "fg:color_blue"
only_with_files = true

[dotnet]
symbol = "󰪮 "
format = '[$symbol$version]($style) '
style = "fg:color_purple"

[golang]
symbol = " "
format = '[[$symbol$version](fg:color_fg0)]($style) '

[nodejs]
symbol = " "
format = '[[$symbol$version](fg:color_fg0)]($style) '

[python]
symbol = " "
format = '[[$symbol$version](fg:color_yellow)]($style)[[(${virtualenv})](fg:color_orange) ]($style)'

[fill]
symbol = " "

[line_break]
disabled = false

[character]
success_symbol = '[\$](bold fg:color_green)'
error_symbol = '[\$](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
