[window]
title = "Alacritty"
dynamic_title = false
padding = { x = 10, y = 10 }

# decorations = "None"

opacity = 1

[font]
normal.family = "UbuntuMono Nerd Font"
bold.family = "UbuntuMono Nerd Font"
size = 15

[shell]
program = "pwsh"

[selection]
save_to_clipboard = true

# gruvbox_material_hard_dark
[colors.primary]
background = '0x1d2021'
foreground = '0xd4be98'
[colors.normal]
black = '0x32302f'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xd8a657'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xd4be98'
[colors.bright]
black = '0x32302f'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xd8a657'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xd4be98'
