"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$golang\
$nodejs\
$python\
$terraform\
$docker_context\
$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[directory]
style = "fg:color_purple"
format = "[$path ]($style)"
truncation_length = 1
# truncation_symbol = "…/"

[git_branch]
symbol = ""
format = '[[git:\(](fg:color_green)[$branch ](fg:color_yellow)]($style)'

[git_status]
format = '[[($all_status)](fg:color_yellow)[( $ahead_behind)](fg:color_red)]($style)[\)](fg:color_green)'

[nodejs]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[c]
symbol = " "
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[rust]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[golang]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0)]($style)'

[python]
symbol = ""
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[terraform]
symbol = "󱁢"
# format = "[ $symbol$workspace]($style)"
format = '[ $symbol $version $workspace]($style) '

[docker_context]
symbol = ""
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[\$](bold fg:color_fg0)'
error_symbol = '[\$](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
